analytics:
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: dw-with-mordern-data-stacks
      dataset: bronze
      keyfile: C:\\Users\\Lyncas\\OneDrive\\Pessoal\\.chaves\\keyfile.json
      threads: 1
      timeout_seconds: 300
      location: us-west1
      priority: interactive
      retries: 1
  target: dev 
